# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Discussion @model {
  id: ID!
  layout: String!
  sentences: [Sentence!] @hasMany
  layoutStates: [LayoutState!] @hasMany
}

type LayoutState @model {
  id: ID!
  layout: String!                            # immutable
  discussion: Discussion! @belongsTo
}

type Sentence @model {
  id: ID!
  content: String!                           # immutable
  discussion: Discussion! @belongsTo         # original
}
