# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Discussion @model @searchable {
  id: ID!
  version: Int!    # == 2
  revision: Int    # incremented on every update
  layout: String!
  goalsSummary: String
  isPrivate: Boolean!
  inviteCode: String @index(name: "byInviteCode")
  users: [User] @manyToMany(relationName: "DiscussionUsers")
  sentences: [Sentence!] @hasMany(indexName: "byDiscussion", fields: ["id"])
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

type Sentence @model {
  id: ID!
  content: String!  # immutable
  searchable: String
  discussionId: ID @index(name: "byDiscussion")
  discussion: Discussion @belongsTo(fields: ["discussionId"])
}

type User @model {
  username: ID! @primaryKey
  discussions: [Discussion] @manyToMany(relationName: "DiscussionUsers")
}

type Subscription {
  onDiscussionById(id: ID!): Discussion
    @aws_subscribe(mutations: ["updateDiscussion"])
}
